### ISSUE TITLE
TokenRoot -> walletOf interface/abi argument naming mismatch

### ISSUE THREAD

**Issue by mnill** [broxus/ton-eth-bridge-token-contracts#4]
In the ITokenRoot.sol you have interface
https://github.com/broxus/tip3/blob/d3c1cd920c0320ffaab03b54c878dd0e06fed3c7/contracts/interfaces/ITokenRoot.sol#L19

but in realization/abi you have:
https://github.com/broxus/tip3/blob/d3c1cd920c0320ffaab03b54c878dd0e06fed3c7/contracts/abstract/TokenRootBase.sol#L67

A little bit confusing, i've used tokenRoot.walletOf({owner: address, answerId: 0}) in sdk and getting encoding error

**Comment by aleksandr-hramcov** [comment]
fixed https://github.com/broxus/tip3/commit/5428f5de4d0c6c40becead9178eecbd847139316
