### ISSUE TITLE
TokenFactory wrong flag

### ISSUE THREAD

**Issue by mnill** [broxus/ton-eth-bridge-token-contracts#5]
https://github.com/broxus/tip3/blob/6503e61880c03fb45741c177c25f4955dca5f0df/contracts/additional/TokenFactory.sol#L95
must be TokenMsgFlag.ALL_NOT_RESERVED

**Comment by aleksandr-hramcov** [comment]
fixed https://github.com/broxus/tip3/commit/5428f5de4d0c6c40becead9178eecbd847139316
